name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        # TODO Add 9, 10, 11, 12, and 13 after Kotlin 1.3.60
        java_version: [1.8]
    steps:
      # In order to have sha256sum on macOS, we need to install coreutils first
      # Use this until coreutils or sha256sum are natively included in macOS on actions https://github.com/actions/virtual-environments/issues/90
      - name: Install coreutils for macOS
        run: brew install coreutils
      - uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc
        run: ./gradlew help
      - name: Build project
        run: ./gradlew assemble --stacktrace
      - name: Run tests
        run: ./gradlew test --stacktrace
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
        with:
          cmd: ./gradlew cAT --stacktrace
          api: 18
          tag: default
          abi: x86
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Espresso-test-report
          path: ./owncloudApp/build/reports/androidTests/connected
      - name: Reclaim memory
        run: ./gradlew --stop && jps|grep -E 'KotlinCompileDaemon|GradleDaemon'| awk '{print $1}'| xargs kill -9
      - name: Final checks
        run: ./gradlew check --stacktrace
      - name: Archive App Lint report
        uses: actions/upload-artifact@v1
        with:
          name: Lint-report
          path: lint-app-report.html


